# fly.toml app configuration file generated for mdow on 2024-11-03T13:48:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mdow'
primary_region = 'lhr'

[build]

[env]
  PORT = '8080'
  DATABASE_URL = "sqlite:/data/mdow.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = "mdow_data"
  destination = "/data"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
